package main

// Integration test of the WP-3.11 job-count exit criterion (DEV-054,
// ARCH-003 §8b): a deterministically generated full-import fixture — N CVEs
// against M inventory components (ch. 17.1: the reference profile is
// 250k CVEs / 10k assets, reduced here to the "≪" proof scale) — driven
// through the fake NVD source (a generated multi-page httptest server, no
// network) and the real full-import path (FullImportSource → RunSource, the
// DEV-067 checkpointed window walk) against a real, short-lived PostgreSQL.
//
// The exit criterion is the matching-job cardinality, read from the real jobs
// table (outbox): a completed full import enqueues exactly ONE matching job —
// the single matching.rebuild fan-in (ADR-012, TR-019 / TAT-15) — and
// decisively NOT in the order of magnitude of the imported CVE count: the
// count is 1 while N is in the thousands (CI) or the hundred thousand
// (reference). A second invocation over the completed source fetches nothing
// and dedupes its fan-in onto the existing job, so the rebuild stays
// exactly-once (ADR-012 point 4).
//
// Scale: the fixture is generated by a pure function of (N, M). The default
// is the CI profile (a few thousand CVEs — bounded so `make ci-test` stays
// fast); set RISKSIGNAL_BULK_SCALE=reference to run the ch. 17.1 reference
// profile (100,000 CVEs / 10,000 components) — the same code path, only the
// two integers differ. The property (matching jobs == 1 and ≪ N) is
// independent of the exact N.
//
// The database server is the compose `db` service (make up) or any other
// PostgreSQL reachable through RISKSIGNAL_TEST_DATABASE_URL; when none is
// reachable the tests skip (newMigratedTestPool), so `go test ./...` stays
// green on machines without the environment.

import (
	"context"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgtype"

	"github.com/xpera/risksignal/internal/adapters/postgres/gen"
	"github.com/xpera/risksignal/internal/adapters/sources/nvd"
	"github.com/xpera/risksignal/internal/application"
	"github.com/xpera/risksignal/internal/platform/clock"
)

// Bulk fixture scales (ch. 17.1). The reference profile is the architecture's
// target; the CI default is the reduced but structurally identical profile
// that keeps `make ci-test` fast. The job-count property holds for both.
const (
	bulkReferenceCVEs       = 100_000
	bulkReferenceComponents = 10_000
	bulkDefaultCVEs         = 5_000
	bulkDefaultComponents   = 1_000

	// bulkJobThreshold is the DEV-067 threshold: a full import enqueues at
	// most one matching job (the single rebuild) plus no per-CVE fan-out.
	bulkJobThreshold = 1
)

// bulkFixtureScale returns the (CVE count, component count) of this run:
// the reference profile when RISKSIGNAL_BULK_SCALE=reference, the CI default
// otherwise.
func bulkFixtureScale() (cves, components int) {
	if strings.EqualFold(strings.TrimSpace(os.Getenv("RISKSIGNAL_BULK_SCALE")), "reference") {
		return bulkReferenceCVEs, bulkReferenceComponents
	}
	return bulkDefaultCVEs, bulkDefaultComponents
}

// bulkRelevanceEvery gives every bulkRelevanceEvery-th generated CVE a
// matching cpe_config so the generated fixture carries an expected hit set
// (ch. 17.2); the other CVEs are minimal records. The job-count metric does
// not depend on this — the fan-in is unconditional — it only keeps the
// fixture representative.
const bulkRelevanceEvery = 1000

// bulkProductName is the deterministic product name of the i-th generated
// component (1-based).
func bulkProductName(i int) string { return fmt.Sprintf("p%05d", i) }

// bulkCVEID is the deterministic CVE id of the i-th generated record (1-based).
func bulkCVEID(i int) string { return fmt.Sprintf("CVE-2026-%07d", i) }

// bulkNvdPage renders one API 2.0 response page of the generated fixture: the
// records [startIndex, startIndex+resultsPerPage) of an N-record set, with the
// terminating empty page past the served set. The shape is the reduced
// {"cve": …} entry the normaliser decodes; every bulkRelevanceEvery-th record
// additionally carries a cpe_config naming one of the M generated components.
func bulkNvdPage(startIndex, n, m int) string {
	const perPage = 2000
	var b strings.Builder
	fmt.Fprintf(&b, `{"resultsPerPage":%d,"startIndex":%d,"totalResults":%d,"vulnerabilities":[`, perPage, startIndex, n)
	first := true
	for i := 0; i < perPage && startIndex+i < n; i++ {
		idx := startIndex + i + 1
		if !first {
			b.WriteByte(',')
		}
		first = false
		if idx%bulkRelevanceEvery == 0 {
			comp := (idx/bulkRelevanceEvery-1)%m + 1
			fmt.Fprintf(&b, `{"cve":{"id":%q,"configurations":[{"nodes":[{"cpeMatch":[{"vulnerable":true,"criteria":"cpe:2.3:a:v:%s:1.0:*:*:*:*:*:*:*"}]}]}]}}`,
				bulkCVEID(idx), bulkProductName(comp))
			continue
		}
		fmt.Fprintf(&b, `{"cve":{"id":%q}}`, bulkCVEID(idx))
	}
	b.WriteString(`]}`)
	return b.String()
}

// serveBulkNvd serves the generated N-record fixture (network-free) and
// counts the requests, so the walk can be asserted.
func serveBulkNvd(n, m int) (*httptest.Server, func() int) {
	var hits int
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		hits++
		w.Header().Set("Content-Type", "application/json")
		start, _ := strconv.Atoi(r.URL.Query().Get("startIndex"))
		if start >= n {
			fmt.Fprintf(w, `{"resultsPerPage":2000,"startIndex":%d,"totalResults":%d,"vulnerabilities":[]}`, start, n)
			return
		}
		_, _ = w.Write([]byte(bulkNvdPage(start, n, m)))
	}))
	return srv, func() int { return hits }
}

// seedBulkComponents inserts m deterministic components under one asset and
// returns the asset id. The components exercise the product index (the
// inventory snapshot the rebuild fan-in hashes is non-trivial).
func seedBulkComponents(t *testing.T, ctx context.Context, q *gen.Queries, m int) pgtype.UUID {
	t.Helper()
	assetID, err := q.UpsertAsset(ctx, gen.UpsertAssetParams{
		ExternalID: "bulk-asset", Source: "cmdb", Type: "server_vm", Name: "Bulk Asset",
		Environment: "production", Criticality: "high", Exposure: "internet",
	})
	if err != nil {
		t.Fatalf("UpsertAsset: %v", err)
	}
	at := pgtype.Timestamptz{Time: sourceRunClockStart, Valid: true}
	for i := 1; i <= m; i++ {
		vendorNorm, productNorm, naturalKey, err := seededComponentKey("v", bulkProductName(i), "1.0")
		if err != nil {
			t.Fatalf("seededComponentKey(%d): %v", i, err)
		}
		if _, err := q.InsertComponent(ctx, gen.InsertComponentParams{
			AssetID: assetID, Vendor: "v", Product: bulkProductName(i), Version: "1.0",
			VendorNorm: vendorNorm, ProductNorm: productNorm, VersionScheme: "unknown",
			NaturalKey: naturalKey, UpdatedAt: at,
		}); err != nil {
			t.Fatalf("InsertComponent(%d): %v", i, err)
		}
	}
	return assetID
}

// TestBulkFullImportEnqueuesExactlyOneMatchingJob is the job-count exit
// criterion (ARCH-003 §8b, TR-019 / TAT-15): a generated N-CVE full import
// over M components completes and enqueues exactly one matching.rebuild job
// (read from the real outbox/jobs table) — one, not N — and a second
// invocation adds nothing.
func TestBulkFullImportEnqueuesExactlyOneMatchingJob(t *testing.T) {
	n, m := bulkFixtureScale()
	t.Logf("bulk fixture scale: N=%d CVEs, M=%d components (RISKSIGNAL_BULK_SCALE=%q)", n, m, os.Getenv("RISKSIGNAL_BULK_SCALE"))

	pool := newMigratedTestPool(t)
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Minute)
	defer cancel()
	clk := clock.NewFakeClock(sourceRunClockStart)
	q := gen.New(pool)

	seedBulkComponents(t, ctx, q, m)

	srv, pageRequests := serveBulkNvd(n, m)
	t.Cleanup(srv.Close)

	sourceID, err := q.UpsertSource(ctx, gen.UpsertSourceParams{
		Type:     "nvd",
		Name:     "nvd-bulk-jobcount",
		Endpoint: pgtype.Text{String: srv.URL, Valid: true},
		Schedule: pgtype.Text{String: "@hourly", Valid: true},
		Enabled:  true,
		Config:   []byte(`{"full_import_since": "2026-09-09T00:00:00Z", "full_import_chunk": "720h"}`),
	})
	if err != nil {
		t.Fatalf("UpsertSource: %v", err)
	}
	srcID := demoUUID(sourceID)
	svc := newSourceRunService(pool, clk)
	adapter := nvd.New(srv.Client().Transport)

	// --- the generated full import ---------------------------------------
	res, err := svc.FullImportSource(ctx, application.FullImportSourceInput{SourceID: srcID, Adapter: adapter})
	if err != nil {
		t.Fatalf("FullImportSource: %v", err)
	}
	if res.Status != application.SourceRunStatusSucceeded || res.Chunks != 1 {
		t.Fatalf("full import = status %s chunks %d, want succeeded with 1 committed window", res.Status, res.Chunks)
	}
	if got, want := pageRequests(), (n+1999)/2000+1; got != want {
		t.Fatalf("page requests = %d, want %d (ceil(N/2000) data pages + the terminating empty page)", got, want)
	}

	// The whole generated CVE population landed, none quarantined.
	if got := countTableRows(t, pool, "vulnerabilities"); got != n {
		t.Fatalf("vulnerability rows = %d, want the generated %d", got, n)
	}
	if got := countTableRows(t, pool, "quarantine"); got != 0 {
		t.Fatalf("quarantine rows = %d, want 0 (the generated records are all valid)", got)
	}

	// --- the job-count metric (read from the real jobs table) ------------
	const matchingRebuild = "matching.rebuild"
	var jobs, recompute int
	if err := pool.QueryRow(ctx,
		"SELECT count(*) FROM outbox WHERE type = $1", matchingRebuild).Scan(&jobs); err != nil {
		t.Fatalf("count matching.rebuild jobs: %v", err)
	}
	if err := pool.QueryRow(ctx,
		"SELECT count(*) FROM outbox WHERE type = $1", "matching.recompute").Scan(&recompute); err != nil {
		t.Fatalf("count matching.recompute jobs: %v", err)
	}
	if jobs != 1 {
		t.Fatalf("matching.rebuild jobs = %d, want exactly 1 (the single fan-in, ADR-012)", jobs)
	}
	if recompute != 0 {
		t.Fatalf("matching.recompute jobs = %d, want 0 (the full import fans in exactly one rebuild)", recompute)
	}
	if res.MatchingJobsEnqueued != jobs {
		t.Fatalf("reported matching jobs = %d, outbox rows = %d — the metric must reflect the jobs table", res.MatchingJobsEnqueued, jobs)
	}
	// ≤ threshold and decisively ≪ N (TR-019): one job, hundreds/thousands of CVEs.
	if jobs > bulkJobThreshold {
		t.Fatalf("matching jobs %d > threshold %d", jobs, bulkJobThreshold)
	}
	if jobs*1000 > n {
		t.Fatalf("matching jobs %d is not ≪ the CVE count %d (want jobs*1000 <= N)", jobs, n)
	}
	t.Logf("job-count metric: %d matching job(s) for %d imported CVEs (threshold %d)", jobs, n, bulkJobThreshold)

	// --- a second invocation fetches nothing and dedupes the fan-in ------
	res2, err := svc.FullImportSource(ctx, application.FullImportSourceInput{SourceID: srcID, Adapter: adapter})
	if err != nil {
		t.Fatalf("FullImportSource (run 2): %v", err)
	}
	if res2.Chunks != 0 || res2.MatchingJobsEnqueued != 0 {
		t.Fatalf("second full import = chunks %d jobs %d, want 0/0 (cursor at now, fan-in deduped)", res2.Chunks, res2.MatchingJobsEnqueued)
	}
	if err := pool.QueryRow(ctx,
		"SELECT count(*) FROM outbox WHERE type = $1", matchingRebuild).Scan(&jobs); err != nil {
		t.Fatalf("count matching.rebuild jobs (run 2): %v", err)
	}
	if jobs != 1 {
		t.Fatalf("matching.rebuild jobs after run 2 = %d, want still exactly 1", jobs)
	}
}
