-- audit_events: the append-only audit trail write (ARCH-001 §1, WP-1b.03).
--
-- There is exactly one write path — append. The table is append-only by
-- design (ch. 13.1, ADR-014): no update or delete statement exists here or
-- in application code, and the production role gets no write grant beyond
-- INSERT/SELECT from I6. Audit rows are written inside the same WithTx
-- transaction as the state change they describe (ARCH-001 §2: one domain
-- command, one transaction), with occurred_at from the injected clock and
-- before/after as minimised snapshots without secrets (ch. 13.5).

-- InsertAuditEvent appends one audit event and returns the stored row. The
-- id is generated by the column default; correlation_id links this row to
-- the outbox row written by the same command. prev_hash/row_hash carry the
-- optional audit hash chain (migration 00012, ARCH-007 §7 control 3b): both
-- are NULL when the chain is disabled, and the AuditRepo.Append caller stamps
-- them from LatestAuditHash + the canonical row bytes when
-- retention.hash_chain_enabled is on.
-- name: InsertAuditEvent :one
INSERT INTO audit_events (
    aggregate_type,
    aggregate_id,
    actor_type,
    actor_id,
    actor_display_name,
    action,
    occurred_at,
    before,
    after,
    correlation_id,
    prev_hash,
    row_hash
)
VALUES (
    @aggregate_type,
    @aggregate_id,
    @actor_type,
    @actor_id,
    @actor_display_name,
    @action,
    @occurred_at,
    @before,
    @after,
    @correlation_id,
    @prev_hash,
    @row_hash
)
RETURNING *;

-- AcquireAuditChainLock takes the transaction-scoped advisory lock that
-- serialises concurrent chained appends (ARCH-007 §7 control 3b): without it
-- two transactions could both read the same LatestAuditHash and fork the
-- chain. It is taken only when retention.hash_chain_enabled is on; the
-- append path is otherwise untouched. The lock releases at commit/rollback.
-- name: AcquireAuditChainLock :exec
SELECT pg_advisory_xact_lock(@key::bigint);

-- GetAuditEventByID reads one audit event by its id — the load step of the
-- governed audit.reveal_identity act (ARCH-005 §7, ADR-014): the command
-- loads the event whose actor_id it resolves. The table stays append-only;
-- this is a read, not a second write path. A missing id is pgx.ErrNoRows
-- (mapped to not-found by the adapter); the reveal then writes nothing.
-- name: GetAuditEventByID :one
SELECT *
FROM audit_events
WHERE id = @id;

-- ListAuditEventsByAggregate reads one aggregate's audit timeline ordered by
-- occurred_at then id (ARCH-006 §3.1, DEV-110): the signal-detail timeline
-- read of the web adapter. It is a read over the append-only table (no
-- second write path) and walks the IX
-- audit_events_aggregate_type_aggregate_id_idx. An aggregate with no event
-- yields no rows — the caller renders an empty timeline, never an error.
-- name: ListAuditEventsByAggregate :many
SELECT *
FROM audit_events
WHERE aggregate_type = @aggregate_type
  AND aggregate_id = @aggregate_id
ORDER BY occurred_at, id;

-- LatestAuditHash reads the row_hash of the newest event that is part of the
-- optional audit hash chain (migration 00012, ARCH-007 §7 control 3b) — the
-- prev_hash a new Append links to when retention.hash_chain_enabled is on.
-- The chain order is the audit trail's stable order (occurred_at, id), the
-- same order the per-aggregate reads use; rows with a NULL row_hash predate
-- the chain (or the chain is off) and are skipped. An empty/unstamped trail
-- is pgx.ErrNoRows (the first chained event links to a NULL/absent prev).
-- name: LatestAuditHash :one
SELECT row_hash
FROM audit_events
WHERE row_hash IS NOT NULL
ORDER BY occurred_at DESC, id DESC
LIMIT 1;

-- ListAuditHashChain returns the whole audit trail in chain order
-- (occurred_at then id) for the end-to-end chain verification (ARCH-007 §7
-- control 3b, §4 AT-015): the verify command recomputes each row's
-- SHA-256(prev_hash ‖ canonical row bytes) and compares it to the stored
-- row_hash. It is a read over the append-only table (no second write path);
-- rows with NULL hashes are included so the verifier can anchor the chain
-- start. An empty trail yields no rows, never an error.
-- name: ListAuditHashChain :many
SELECT *
FROM audit_events
ORDER BY occurred_at, id;
