-- audit_events: the append-only audit trail write (ARCH-001 §1, WP-1b.03).
--
-- There is exactly one write path — append. The table is append-only by
-- design (ch. 13.1, ADR-014): no update or delete statement exists here or
-- in application code, and the production role gets no write grant beyond
-- INSERT/SELECT from I6. Audit rows are written inside the same WithTx
-- transaction as the state change they describe (ARCH-001 §2: one domain
-- command, one transaction), with occurred_at from the injected clock and
-- before/after as minimised snapshots without secrets (ch. 13.5).

-- InsertAuditEvent appends one audit event and returns the stored row. The
-- id is generated by the column default; correlation_id links this row to
-- the outbox row written by the same command.
-- name: InsertAuditEvent :one
INSERT INTO audit_events (
    aggregate_type,
    aggregate_id,
    actor_type,
    actor_id,
    actor_display_name,
    action,
    occurred_at,
    before,
    after,
    correlation_id
)
VALUES (
    @aggregate_type,
    @aggregate_id,
    @actor_type,
    @actor_id,
    @actor_display_name,
    @action,
    @occurred_at,
    @before,
    @after,
    @correlation_id
)
RETURNING *;

-- GetAuditEventByID reads one audit event by its id — the load step of the
-- governed audit.reveal_identity act (ARCH-005 §7, ADR-014): the command
-- loads the event whose actor_id it resolves. The table stays append-only;
-- this is a read, not a second write path. A missing id is pgx.ErrNoRows
-- (mapped to not-found by the adapter); the reveal then writes nothing.
-- name: GetAuditEventByID :one
SELECT *
FROM audit_events
WHERE id = @id;

-- ListAuditEventsByAggregate reads one aggregate's audit timeline ordered by
-- occurred_at then id (ARCH-006 §3.1, DEV-110): the signal-detail timeline
-- read of the web adapter. It is a read over the append-only table (no
-- second write path) and walks the IX
-- audit_events_aggregate_type_aggregate_id_idx. An aggregate with no event
-- yields no rows — the caller renders an empty timeline, never an error.
-- name: ListAuditEventsByAggregate :many
SELECT *
FROM audit_events
WHERE aggregate_type = @aggregate_type
  AND aggregate_id = @aggregate_id
ORDER BY occurred_at, id;
